qcom_scm: hide Kconfig symbol
Bugzilla: https://bugzilla.redhat.com/2101563

commit 424953cf3c6657f1e67e1a2c5d6e3bb518ea4e9a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Sep 28 09:50:27 2021 +0200

    qcom_scm: hide Kconfig symbol

    Now that SCM can be a loadable module, we have to add another
    dependency to avoid link failures when ipa or adreno-gpu are
    built-in:

    aarch64-linux-ld: drivers/net/ipa/ipa_main.o: in function `ipa_probe':
    ipa_main.c:(.text+0xfc4): undefined reference to `qcom_scm_is_available'

    ld.lld: error: undefined symbol: qcom_scm_is_available
    >>> referenced by adreno_gpu.c
    >>>               gpu/drm/msm/adreno/adreno_gpu.o:(adreno_zap_shader_load) in archive drivers/built-in.a

    This can happen when CONFIG_ARCH_QCOM is disabled and we don't select
    QCOM_MDT_LOADER, but some other module selects QCOM_SCM. Ideally we'd
    use a similar dependency here to what we have for QCOM_RPROC_COMMON,
    but that causes dependency loops from other things selecting QCOM_SCM.

    This appears to be an endless problem, so try something different this
    time:

     - CONFIG_QCOM_SCM becomes a hidden symbol that nothing 'depends on'
       but that is simply selected by all of its users

     - All the stubs in include/linux/qcom_scm.h can go away

     - arm-smccc.h needs to provide a stub for __arm_smccc_smc() to
       allow compile-testing QCOM_SCM on all architectures.

     - To avoid a circular dependency chain involving RESET_CONTROLLER
       and PINCTRL_SUNXI, drop the 'select RESET_CONTROLLER' statement.
       According to my testing this still builds fine, and the QCOM
       platform selects this symbol already.

    Acked-by: Kalle Valo <kvalo@codeaurora.org>
    Acked-by: Alex Elder <elder@linaro.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Conflicts:
    Commit not backported introduce exported functions: de3438c47a8d ("firmware: qcom_scm: Introduce SCM calls to access LMh")
    Commit applied out-of-order: 4382c73a12b4 ("firmware: qcom_scm: QCOM_SCM should depend on ARCH_QCOM")
Signed-off-by: Eric Chanudet <echanude@redhat.com>