scsi: ufs: core: SCSI_UFS_HWMON depends on HWMON=y
Bugzilla: https://bugzilla.redhat.com/2102378

commit 60c98a87fcaad9e71b835d2096e6665543cfe2e1
Author: Anders Roxell <anders.roxell@linaro.org>
Date:   Mon Sep 27 10:46:15 2021 +0200

    scsi: ufs: core: SCSI_UFS_HWMON depends on HWMON=y

    When building an allmodconfig kernel, the following build error shows up:

    aarch64-linux-gnu-ld: drivers/scsi/ufs/ufs-hwmon.o: in function `ufs_hwmon_probe':
    /kernel/next/drivers/scsi/ufs/ufs-hwmon.c:177: undefined reference to `hwmon_device_register_with_info'
    /kernel/next/drivers/scsi/ufs/ufs-hwmon.c:177:(.text+0x510): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `hwmon_device_register_with_info'
    aarch64-linux-gnu-ld: drivers/scsi/ufs/ufs-hwmon.o: in function `ufs_hwmon_remove':
    /kernel/next/drivers/scsi/ufs/ufs-hwmon.c:195: undefined reference to `hwmon_device_unregister'
    /kernel/next/drivers/scsi/ufs/ufs-hwmon.c:195:(.text+0x5c8): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `hwmon_device_unregister'
    aarch64-linux-gnu-ld: drivers/scsi/ufs/ufs-hwmon.o: in function `ufs_hwmon_notify_event':
    /kernel/next/drivers/scsi/ufs/ufs-hwmon.c:206: undefined reference to `hwmon_notify_event'
    /kernel/next/drivers/scsi/ufs/ufs-hwmon.c:206:(.text+0x64c): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `hwmon_notify_event'
    aarch64-linux-gnu-ld: /home/anders/src/kernel/next/drivers/scsi/ufs/ufs-hwmon.c:209: undefined reference to `hwmon_notify_event'
    /kernel/next/drivers/scsi/ufs/ufs-hwmon.c:209:(.text+0x66c): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `hwmon_notify_event'

    Since SCSI_UFS_HWMON can't be built as a module, SCSI_UFS_HWMON has to
    depend on HWMON=y.

    Link: https://lore.kernel.org/r/20210927084615.1938432-1-anders.roxell@linaro.org
    Fixes: e88e2d32200a ("scsi: ufs: core: Probe for temperature notification support")
    Also-reported-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Acked-by: Avri Altman <avri.altman@wdc.com>
    Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Eric Chanudet <echanude@redhat.com>