scsi: ufs: mediatek: Avoid sched_clock() misuse
Bugzilla: https://bugzilla.redhat.com/2102378

commit bb4a8dcb4e9498deccaf7b257449044968e514c7
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Oct 18 15:20:01 2021 +0200

    scsi: ufs: mediatek: Avoid sched_clock() misuse

    sched_clock() is not meant to be used in portable driver code, and assuming
    a particular clock frequency is not how this is meant to be used. It also
    causes a build failure because of a missing header inclusion:

    drivers/scsi/ufs/ufs-mediatek.c:321:12: error: implicit declaration of function 'sched_clock' [-Werror,-Wimplicit-function-declaration]
            timeout = sched_clock() + retry_ms * 1000000UL;

    A better interface to use here ktime_get_mono_fast_ns(), which works mostly
    like ktime_get() but is safe to use inside of a suspend callback.

    Link: https://lore.kernel.org/r/20211018132022.2281589-1-arnd@kernel.org
    Fixes: 9561f58442e4 ("scsi: ufs: mediatek: Support vops pre suspend to disable auto-hibern8")
    Reviewed-by: Stanley Chu <stanley.chu@mediatek.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Eric Chanudet <echanude@redhat.com>